# Generated by Django 4.1.2 on 2023-05-11 15:02
from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from datetime import datetime, timedelta
import time

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='alibekalihan71@gmail.com',
    password='SsNn5678+-@', 
    last_login=datetime.now())
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-', email='fastfood130523@mail.ru', first_name='Менеджер', last_name='', last_login=datetime.now())
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Простые пользователи (заявители) id3-27
    user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Дина', last_name='Мусина', last_login=datetime.now())
    user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Адия', last_name='Жунусова', last_login=datetime.now())
    user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айнура', last_name='Кенина', last_login=datetime.now())
    user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Рустем', last_name='Какимов', last_login=datetime.now())
    user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Алишер', last_name='Кабдуалиев', last_login=datetime.now())
    user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Бауржан', last_name='Арыкбаев', last_login=datetime.now())
    user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Алишер', last_name='Танатаров', last_login=datetime.now())
    user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Мерует', last_name='Искакова', last_login=datetime.now())
    user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева', last_login=datetime.now())
    user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Ақжарқын', last_name='Сансызбаева', last_login=datetime.now())
    user = User.objects.create_user(username='user11', password='Uu0066+-', email='user11@mail.ru', first_name='Арайлым', last_name='Алматова', last_login=datetime.now())
    user = User.objects.create_user(username='user12', password='Uu0066+-', email='user12@mail.ru', first_name='Айгерім', last_name='Дүйсенбиева', last_login=datetime.now())
    user = User.objects.create_user(username='user13', password='Uu0066+-', email='user13@mail.ru', first_name='Салтанат', last_name='Зиноллаева', last_login=datetime.now())
    user = User.objects.create_user(username='user14', password='Uu0066+-', email='user14@mail.ru', first_name='Сейтқасым', last_name='Болат', last_login=datetime.now())
    user = User.objects.create_user(username='user15', password='Uu0066+-', email='user15@mail.ru', first_name='Сара', last_name='Фазилова', last_login=datetime.now())
    user = User.objects.create_user(username='user16', password='Uu0066+-', email='user16@mail.ru', first_name='Бектас', last_name='Ерсейіт', last_login=datetime.now())
    user = User.objects.create_user(username='user17', password='Uu0066+-', email='user17@mail.ru', first_name='Диас', last_name='Мырзаш', last_login=datetime.now())
    user = User.objects.create_user(username='user18', password='Uu0066+-', email='user18@mail.ru', first_name='Нұржан', last_name='Жүрсінбек', last_login=datetime.now())
    user = User.objects.create_user(username='user19', password='Uu0066+-', email='user19@mail.ru', first_name='Дина', last_name='Жағыпар', last_login=datetime.now())
    user = User.objects.create_user(username='user20', password='Uu0066+-', email='user20@mail.ru', first_name='Жастілек', last_name='Жасталап', last_login=datetime.now())
    user = User.objects.create_user(username='user21', password='Uu0066+-', email='user21@mail.ru', first_name='Еркебұлан', last_name='Қадыхан', last_login=datetime.now())
    user = User.objects.create_user(username='user22', password='Uu0066+-', email='user22@mail.ru', first_name='Молдир', last_name='Бутабекова', last_login=datetime.now())
    user = User.objects.create_user(username='user23', password='Uu0066+-', email='user23@mail.ru', first_name='Аружан', last_name='Таурбекова', last_login=datetime.now())
    user = User.objects.create_user(username='user24', password='Uu0066+-', email='user24@mail.ru', first_name='Алтынай', last_name='Қожанова', last_login=datetime.now())
    user = User.objects.create_user(username='user25', password='Uu0066+-', email='user25@mail.ru', first_name='Эльнара', last_name='Иминова', last_login=datetime.now())
    print("Созданы простые пользователи")

    ##### Каталог товаров + Продажа + Доставка #####

    Category = apps.get_model("food", "Category")
    Catalog = apps.get_model("food", "Catalog")
    Sale = apps.get_model("food", "Sale")
    Delivery = apps.get_model("food", "Delivery")

    category = Category()
    category.title='Пицца'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Маргарита'
    catalog.details='Помидоры, сыр моцарелла'
    catalog.price=1600
    catalog.photo='images/food1.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 3
    sale.rating = 5
    sale.details='Маргарита-классика пиццы,простая и вкусная!Для меня же,она очень простая!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Деревенская'
    catalog.details='Фарш, грибы, зелень, сыр моцарелла'
    catalog.price=2400
    catalog.photo='images/food2.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 4
    sale.rating = 5
    sale.details='Мне очень понравилось вкусное и нежное тесто, края были хрустящими. Единственное, картошка была немного сыровата. Пришлось по вкусу оригинальное наполнение, обильная, незабываемая начинка. '
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Saturo'
    catalog.details='Копченная курица, охотничьи сосиски, помидор, сыр моцарелла'
    catalog.price=2200
    catalog.photo='images/food3.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 5
    sale.rating = 5
    sale.details='Начинки на кусочке достаточно!На вкус чувствуются томаты и базилик с орегано,классическое сочитание!Соуса и сыра достаточно много,он приятно тянется!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=28)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()
    
    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Охотничья'
    catalog.details='Охотничьи сосиски, грибы, зеленый лук, сыр моцарелла'
    catalog.price=2200
    catalog.photo='images/food4.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 6
    sale.rating = 5
    sale.details='Выбрала пиццу Охотничья. В меню заявлены такие ингредиенты как грибы, зеленй лук, охотничьи колбаски и сыр моцарелла, вполне хороший набор продуктов чтобы сделать вкусную пиццу.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=27)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Family'
    catalog.details='Болгарский перец, помидор, колбаса, сыр моцарелла'
    catalog.price=2200
    catalog.photo='images/food5.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 7
    sale.rating = 5
    sale.details='Заказывал пиццу, все очень вкусно. Повару большой респект. Всегда выбираем это заведение,и всегда очень довольны!! Спасибо вам за ваш труд, ваше блюдо это бомба'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=26)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    category = Category()
    category.title='Суши'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Цезарь Темпура'
    catalog.details='Копченная курица, огурцы, творожный сыр'
    catalog.price=1900
    catalog.photo='images/food6.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 6
    sale.rating = 5
    sale.details='Что меня не убьёт, то переварится))) Довольно неплохой ролл, в который положили соус не заявленный в рецепте, или мне показалось?'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=25)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Кюрино Темпура'
    catalog.details='Огурцы, творожный сыр'
    catalog.price=1400
    catalog.photo='images/food7.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 7
    sale.rating = 5
    sale.details='В целом, вкусная и неприторная вещь. Рекомендую любителям классических роллов '
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=24)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Черный Сёгун'
    catalog.details='Сёмга, огурцы, творожный сыр, черная икра'
    catalog.price=1900
    catalog.photo='images/food8.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 8
    sale.rating = 5
    sale.details='Роллы вкусные. Цены нормальные.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=23)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Чиз Ролл'
    catalog.details='Сёмга, огурец, творожный сыр, плавленный сыр сверху'
    catalog.price=1850
    catalog.photo='images/food9.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 9
    sale.rating = 5
    sale.details='Это самые лучшие и вкусные суши, роллы и супы. Спасибо вам огромное !'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=22)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
 
    catalog = Catalog()
    catalog.category = category
    catalog.title='Эби Фурай'
    catalog.details='Болгарский перец, креветки, сырная шапочка'
    catalog.price=1900
    catalog.photo='images/food10.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 10
    sale.rating = 5
    sale.details='После этих суши больше не захочешь никаких других!!! Действительно очень вкусно!! Спасибо за ваш труд и любовь к своему делу!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=21)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    print("Catalog Ok")

    ##### Новости #####
    News = apps.get_model("food", "News")
    
    news = News()
    news.daten = datetime.now() - timedelta(days=35)
    news.title = 'Закажи 2 пиццы и 3-ю получи в подарок'
    news.details = """Закажи 2 пиццы и 3-ю получи в подарок
    """
    news.photo = 'images/news1.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=30)
    news.title = 'Скидка 10% на самовывоз'
    news.details =  """Скидка 10% на самовывоз
    """
    news.photo = 'images/news2.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=25)
    news.title = 'Скидка 10 % день рождения'
    news.details = """Скидка 10 % день рождения
    """
    news.photo = 'images/news3.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=20)
    news.title = '-5% ЗА РЕГИСТРАЦИЮ НА САЙТЕ'
    news.details = """-5% ЗА РЕГИСТРАЦИЮ НА САЙТЕ
    """
    news.photo = 'images/news4.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=15)
    news.title = '15% НА САМОВЫВОЗ'
    news.details = """Получи скидку 15% на все товары, при самовывозе.
    """
    news.photo = 'images/news5.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=10)
    news.title = 'Битва Вкусов'
    news.details = """Теперь можно попробовать две разные пиццы заказав только одну. Мы выпекаем два разных вкуса на одном корже.
    """
    news.photo = 'images/news6.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=5)
    news.title = '3+1'
    news.details = """Закажи 3 любые пиццы (30 см) и получи в подарок пиццу "Duetto" (24 см)!
    """
    news.photo = 'images/news7.jpeg' 
    news.save()
    
    print("News Ok")



class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),
        migrations.RunSQL("""CREATE VIEW view_catalog AS
                        SELECT catalog.id, catalog.category_id, category.title AS category, catalog.title, catalog.details, catalog.price, catalog.photo, 
                        (SELECT AVG(rating) FROM sale WHERE sale.catalog_id = catalog.id) AS avg_rating
                        FROM catalog LEFT JOIN category ON catalog.category_id = category.id;"""),
        migrations.RunSQL("""CREATE VIEW view_sale AS
                        SELECT sale.id, username, saleday, catalog_id, view_catalog.category, view_catalog. title, view_catalog.photo, sale.price, sale.quantity, sale.price*sale.quantity AS total, user_id, rating, sale.details,
                        (SELECT strftime('%d.%m.%Y',deliveryday) || ' - ' || movement FROM delivery WHERE sale_id = sale.id AND deliveryday = (SELECT MAX(deliveryday) AS Expr1 FROM delivery AS S WHERE  (sale_id = sale.id) )) AS final
                        FROM sale LEFT JOIN view_catalog ON sale.catalog_id = view_catalog.id
                        LEFT JOIN auth_user ON sale.user_id = auth_user.id"""),
        #migrations.RunSQL("""CREATE VIEW view_sale AS
        #                SELECT sale.id, username, saleday, catalog_id, view_catalog.category, view_catalog. title, view_catalog.photo, sale.price, sale.quantity, sale.price*sale.quantity AS total, user_id, rating, sale.details,
        #                (SELECT to_char( deliveryday, 'DD.MM.YYYY') || ' - ' || movement FROM delivery WHERE sale_id = sale.id AND deliveryday = (SELECT MAX(deliveryday) AS Expr1 FROM delivery AS S WHERE  (sale_id = sale.id) )) AS final
        #                FROM sale LEFT JOIN view_catalog ON sale.catalog_id = view_catalog.id
        #                LEFT JOIN auth_user ON sale.user_id = auth_user.id"""),
    ]

